### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by bradintheusa** [victorvaldez5/vite-library-tutorial#1]
Hi

In your app.vue you reference it directly. When I try to use via my package.json

````
  "dependencies": {
    "vue": "^3.2.31",
    "VButton" : "file:../vite-library-tutorial/"
````

I get 
```
src/App.vue:4:21 - error TS7016: Could not find a declaration file for module 'VButton'. 'D:/GitHub/pubic/vue3Components/vite-library-tutorial/dist/my-lib.umd.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vite-library-tutorial` if it exists or add a new declaration (.d.ts) file containing `declare module 'VButton';`

4 import VButton from 'VButton';
```

Any ideas?

**Comment by victorvaldez5** [comment]
It looks like you're trying to do something with Typescript, and the compiler doesn't like it since this isn't a typescript package. 

Also it doesn't look you're installing the package correctly. Your package.JSON should install the library that you built, not the individual components

**Comment by bradintheusa** [comment]
Thank you. This has pointed me in the right direction.
